on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/code'
    steps:
      - name: git_checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PSP_RE_DEPLOY_PRIVKEY }}
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
